### ISSUE TITLE
Add Endless Key configuration

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/eos-kolibri#20]
The [eos-kolibri-system-helper](https://github.com/endlessm/eos-kolibri/tree/eos5.0#eos-kolibri-system-helper) package adds system-wide configuration specific to org.learningequality.Kolibri. We need to add an Endless Key flavour, adding the same configuration but for org.endlessos.Key. The Endless Key variant must use a different Kolibri data directory, but it may use the same "kolibri" system user. The build system here is cleverly prepared for building with a different flatpak app ID, so that should be straightforward.

Optionally, it would be nice to do the same thing for eos-kolibri-tools, again building Endless Key versions of the same tools. In some cases, the build system will need to be modified to rename files from eos-kolibri- to eos-endless-key-.

**Comment by starnight** [comment]
According to the discussion in [Create a flatpak manifest for an Endless Key app](https://github.com/endlessm/endless-key-flatpak/issues/4), should we use the configuration as `org.endlessos.Key`?

**Comment by dbnicholson** [comment]
> According to the discussion in [Create a flatpak manifest for an Endless Key app](https://github.com/endlessm/endless-key-flatpak/issues/4), should we use the configuration as `org.endlessos.Key`?

Indeed! I updated the PR description to match.

**Comment by dbnicholson** [comment]
> Which means org.learningequality.Kolibri flatpak maintains the Home directory path.

That's when it's used as a session service. The point here is that we want a **system** service so that the server and data can be shared between users and we can preseed data in images.

```
$ dbus-send --system --dest=org.learningequality.Kolibri.Daemon --print-reply /org/learningequality/Kolibri/Daemon/Main org.freedesktop.DBus.Properties.Get string:org.learningequality.Kolibri.Daemon string:KolibriHome
method return time=1692796473.217399 sender=:1.175 -> destination=:1.176 serial=16 reply_serial=2
   variant       string "/var/lib/kolibri/data"
```

We need a different system homedir for the Endless Key so that `/var/lib/kolibri/data` can continue to be used by `org.learningequality.Kolibri`.

**Comment by dbnicholson** [comment]
The more I think about this, the more I think we may need to just fork this repo. If everything is managed at build time *and* we want to retain the original `org.learningequality.Kolibri` interfaces in EOS, then I think we have 2 options:

* Change the debian packaging so that there are 2 binary packages, `eos-kolibri-system-helper` and `endless-key-system-helper`. Build the code once per binary package with the appropriate build settings.
* Fork this to a new `endless-key-system-helper` repo, change all the defaults and tool names, and provide a single `endless-key-system-helper` binary package.

@dylanmccall is the intention that we want to keep providing the original `eos-kolibri` daemon and tools using the `org.learningequality.Kolibri` names + provide a daemon and tools using the `org.endlessos.Key` names?

**Comment by starnight** [comment]
I make it adding xx-endlesskey-oo things first #21.  We can revert the commit if we want to have two packages, or a single `endless-key-system-helper` package.

**Comment by starnight** [comment]
Verification is covered by https://github.com/endlessm/eos-kolibri/pull/27#issuecomment-1702252915
