### ISSUE TITLE
Backport Endless Key changes to EOS 5

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/eos-kolibri#28]
The changes to support the Endless Key flatpak need to be backported to EOS 5 prior to releasing the flatpak. Otherwise users on released EOS won't get the full shared data experience.

Can we test that this works on master and then fast-forward eos5.0 to master?

**Comment by starnight** [comment]
After test the the testing build from https://github.com/flathub/flathub/pull/4481#issuecomment-1718706603 on latest EOS master
```
flatpak install https://dl.flathub.org/build-repo/46484/org.endlessos.Key.flatpakref
```

The major path is happy!  It does use `/var/lib/endless-key/data` as the home directory.  SQLite and other things are there.

**Comment by starnight** [comment]
> Can we test that this works on master and then fast-forward eos5.0 to master?

I think yes!

**Comment by starnight** [comment]
I did fast-forward eos5.0 to master.

**Comment by starnight** [comment]
I triggered https://ci.endlessos.org/view/OSTree/job/ostree-build-amd64/17771/ to build new EOS 5.0 OSTree, including the new **eos-kolibri**.
The new EOS 5.0 OSTree Build ID is "230914-073502".

Verified pass as https://github.com/endlessm/eos-kolibri/issues/28#issuecomment-1718873491.
