### ISSUE TITLE
Disable XDG_DATA_DIRS additions for Endless Key

### ISSUE THREAD

**Issue by dylanmccall** [endlessm/eos-kolibri#29]
For the Endless Key app, we want to remove channel-specific desktop launchers and search providers.

**Comment by dbnicholson** [comment]
I think https://github.com/endlessm/eos-kolibri/compare/29-remove-endless-key-data-dirs needs a PR, right?

**Comment by dbnicholson** [comment]
Sadly, this will need another OS release.

**Comment by dbnicholson** [comment]
If you're confident in this, can you fast-forward the eos5.0 branch?

**Comment by dylanmccall** [comment]
Yes! Done :)

**Comment by erikos** [comment]
Anything left to do here, or can we archive this?

**Comment by dbnicholson** [comment]
> Anything left to do here, or can we archive this?

I think we want to actually QA it on an EOS 5 system. It would be pretty unfortunate to make a 5.0.7 release only to find that this didn't actually work.

https://phabricator.endlessm.com/T34930
